---
# 1. LiteLLM (The Router)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: sovereign-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest
        args: ["--config", "/app/config.yaml", "--port", "4000", "--detailed_debug"]
        ports:
        - containerPort: 4000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gui-secrets
                key: DATABASE_URL
          - name: LITELLM_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: gui-secrets
                key: MASTER_KEY
          - name: LITELLM_SALT_KEY
            valueFrom:
              secretKeyRef:
                name: gui-secrets
                key: SALT_KEY
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config

---
# 2. LiteLLM Service (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: sovereign-ai
spec:
  type: NodePort
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400

---
# 3. Open WebUI (The Interface)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: sovereign-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        env:
        - name: OPENAI_API_BASE_URL
          value: "http://litellm:4000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gui-secrets
              key: MASTER_KEY
        - name: ENABLE_RAG_WEB_SEARCH
          value: "False"
        - name: LOG_LEVEL
          value: "DEBUG"
# --- LDAP "KITCHEN SINK" CONFIG ---
        - name: ENABLE_LDAP
          value: "true"
        - name: LDAP_SERVER_HOST
          value: "10.10.10.11"  # e.g., 10.10.10.10
        - name: LDAP_SERVER_PORT
          value: "389"
        - name: LDAP_BIND_DN
          value: "CN=svc-openwebui,CN=Users,DC=sovereign,DC=lab"
        - name: LDAP_BIND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-secrets
              key: bind-password
        - name: LDAP_USER_BASE
          value: "DC=sovereign,DC=lab"
        - name: LDAP_USER_FILTER
          value: "(&(objectClass=user)(sAMAccountName=%s))"
        - name: LDAP_USER_ATTRIBUTE
          value: "sAMAccountName"
        - name: LDAP_MAIL_ATTRIBUTE
          value: "mail"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: webui-storage
          mountPath: /app/backend/data
      volumes:
      - name: webui-storage
        hostPath:
          path: /mnt/sovereign-storage/open-webui-data
          type: DirectoryOrCreate

---
# 4. Open WebUI Service
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: sovereign-ai
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
