apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:24.10-vllm-python-py3
        resources:
          limits:
            nvidia.com/gpu: 6 # Claim the whole rig, Triton will sub-allocate
        args: ["tritonserver", "--model-repository=/models", "--log-verbose=1"]
        volumeMounts:
        - name: model-repo
          mountPath: /models
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: model-repo
        hostPath:
          path: /mnt/sovereign-storage/models
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
